version: '3'
services:
  ngrok:
    tty: true
    build: ./ngrok
    command: bash -c "python3 replace-env.py ngrok-config.yml.template ngrok-config.yml && ./ngrok start jupyter -config=ngrok-config.yml"
    env_file:
      - .env
    networks:
      - jupyter
    restart: on-failure
  jupyter:
    tty: true
    build: dlc-darknet-gpu
    command: bash -c "jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root --NotebookApp.token='$NOTEBOOK_PASSWORD' --NotebookApp.allow_origin=* --NotebookApp.notebook_dir=/"
    ports:
      - 8888:8888
    env_file:
      - .env
    networks:
      - jupyter
networks:
  jupyter:
