version: '2.3'
services:
  ngrok:
    tty: true
    stdin_open: true
    build: ./ngrok
    command: ./run.sh
    env_file:
      - .env
    networks:
      - tf1-dlc-darknet
      - tf2

  tf1-dlc-darknet:
    tty: true
    stdin_open: true
    build: tf1-dlc-darknet
    command: ./run.sh 
    ports:
      - 8888:8888
    env_file: 
      - .env
    networks:
      - tf1-dlc-darknet
    volumes:
      - ${SHARED_VOLUME}:/shared
    environment:
      - NOTEBOOK_TITLE_POSTFIX=DLC
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
        
  tf2:
    tty: true
    stdin_open: true
    build: tf2
    command: ./run.sh 
    ports:
      - 8889:8888
    env_file:
      - .env
    networks:
      - tf2
    volumes:
      - ${SHARED_VOLUME}:/shared
    environment:
      - NOTEBOOK_TITLE_POSTFIX=TF2
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  py39:
    tty: true
    stdin_open: true
    build: py39
    command: ./run.sh 
    ports:
      - 8890:8888
    env_file:
      - .env
    networks:
      - py39
    volumes:
      - ${SHARED_VOLUME}:/shared
    environment:
      - NOTEBOOK_TITLE_POSTFIX=py39
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    
networks:
  tf1-dlc-darknet:
  tf2:
  py39:
